services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acmeapp-backend
    env_file:
      - .env
    ports:
      - "3003:3003"
    restart: always
    volumes:
      - app_logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        labels: "service=nestjs"
    networks:
      - app-network

  promtail:
    image: grafana/promtail:3.0.0
    container_name: zii-be-promtail
    restart: unless-stopped
    volumes:
      - ./observability/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - app_logs:/app/logs:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
      - app
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.4.0
    container_name: zii-be-grafana
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-Gr4f4n4Pr0d2024!@#}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    networks:
      - app-network
