server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - json:
          source: output
          expressions:
            level:
            message:
            context:
            timestamp:
      - labels:
          stream:
          level:
          context:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: message

  # AcmeApp application file logs
  - job_name: acmeapp-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: acmeapp-backend
          __path__: /app/logs/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            context: context
            message: message
            stack: stack
            cid: cid
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          context:
          cid:

  # System logs (optional)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
